export function Table(){
  return(
    <>
      <table border={1} className="w-[100%] border">
        <thead>
          <tr>
            <th>sdf</th>
            <th>sdf</th>
            <th>sdf</th>
            <th>sdf</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>sdfsdf</td>
            <td>sdfsdf</td>
            <td>sdfsdf</td>
            <td>sdfsdf</td>
          </tr>
          <tr>
            <td>sdfsdf</td>
            <td>sdfsdf</td>
            <td>sdfsdf</td>
            <td>sdfsdf</td>
          </tr>
        </tbody>
      </table>
    </>
  )
}